import type { ReactNode } from "react";
import { Link } from "../router";
import { REPO_URL } from "../ui";

const UPDATED = "September 28, 2026";

function LegalPage({ title, children }: { title: string; children: ReactNode }) {
  return (
    <main id="main" className="container narrow page-pad legal">
      <h1>{title}</h1>
      <p className="muted">Last updated: {UPDATED}</p>
      <p className="notice">Template: the site owner must review this with their own details before a public launch.</p>
      {children}
    </main>
  );
}

export function Privacy() {
  return (
    <LegalPage title="Privacy Policy">
      <h2>What we collect</h2>
      <ul>
        <li><b>Account:</b> your name, email address, role and a salted hash of your password (never the password itself).</li>
        <li><b>Learning progress:</b> which lessons you completed and when, and your last sign-in time.</li>
        <li><b>Chat messages:</b> what you send to ShopBot and its replies, kept for up to 24 hours to maintain the conversation. Thumbs-up/down feedback is stored with the related message to improve the evaluations.</li>
        <li><b>Technical data:</b> request logs and metrics (for example IP address for rate limiting, latency, errors) used to run and protect the service.</li>
      </ul>
      <h2>How chat messages are processed</h2>
      <p>
        To answer you, ShopBot sends your messages to a third-party AI model provider (for example Groq). Do not type personal, financial or
        confidential information into the chat. ShopBot masks card numbers it detects, but you should never enter real ones.
      </p>
      <h2>Browser storage</h2>
      <p>We use your browser's local storage only for your sign-in token, theme choice and current conversation id. We don't use advertising or tracking cookies.</p>
      <h2>Your choices</h2>
      <p>You can ask for your account and data to be deleted, or for a copy of your data, by <a href={`${REPO_URL}/issues`} target="_blank" rel="noreferrer">contacting us</a>.</p>
      <h2>Security</h2>
      <p>Passwords are hashed with PBKDF2, sessions use signed tokens that expire, and sign-in attempts are rate-limited.</p>
    </LegalPage>
  );
}

export function Terms() {
  return (
    <LegalPage title="Terms of Use">
      <h2>The service</h2>
      <p>AI Testing Lab is an educational service for learning how to test AI applications. ShopBot, ShopEase, and all products, customers and orders shown are fictional demo data.</p>
      <h2>Your account</h2>
      <p>Keep your password private. You're responsible for activity under your account. We may disable accounts that abuse the service.</p>
      <h2>Acceptable use</h2>
      <ul>
        <li>Adversarial prompts (prompt injection, jailbreaks) are welcome inside the chat; that is part of the course.</li>
        <li>Don't attack the infrastructure: no denial-of-service, scraping at scale, attempts to access other users' data, or bypassing rate limits.</li>
        <li>Don't enter real personal, payment or confidential information.</li>
      </ul>
      <h2>AI output</h2>
      <p>ShopBot's answers are generated by AI and may be wrong. Some content is deliberately flawed for teaching purposes. Nothing in the lab is professional advice.</p>
      <h2>Availability</h2>
      <p>The service is provided "as is", without warranties, and may change or be unavailable at any time.</p>
    </LegalPage>
  );
}

export function NotFound() {
  return (
    <main id="main" className="container narrow page-pad center-page">
      <span className="big-code gradient-text">404</span>
      <h1>Page not found</h1>
      <p className="muted">The page you're looking for doesn't exist or has moved.</p>
      <Link to="/" className="btn btn-primary">Back to home</Link>
    </main>
  );
}

export function Forbidden() {
  return (
    <main id="main" className="container narrow page-pad center-page" data-testid="forbidden">
      <span className="big-code gradient-text">403</span>
      <h1>Admins only</h1>
      <p className="muted">Your account doesn't have access to this page.</p>
      <Link to="/lab" className="btn btn-primary">Go to dashboard</Link>
    </main>
  );
}
